KEYCLOAK_REALM: datmt-test-realm
KEYCLOAK_URL: http://localhost:18080/auth
#keycloak
keycloak:
    realm: datmt-test-realm
    auth-server-url: http://localhost:18080/auth/
    ssl-required: external
    resource: spring-boot-client
    credentials:
        secret: 1dd4da9f-286d-4fce-b6a4-c035cc4d5e5b
    use-resource-role-mappings: true
    bearer-only: true

spring:
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    security:
        oauth2:
            resourceserver:
                jwt:
                    jwk-set-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs
                    issuer-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}

logging:
    level:
        org.springframework.security: trace
